# =========================
# MAP SERVER
# =========================
map_server:
  ros__parameters:
    use_sim_time: false
        yaml_filename: "/home/homebot/test_ws/src/homebot_0/maps/my_map.yaml"

# =========================
# AMCL (Localization)
# =========================
amcl:
  ros__parameters:
    use_sim_time: false

# =========================
# BT NAVIGATOR (Behavior Trees)
# =========================
bt_navigator:
  ros__parameters:
    use_sim_time: false

# =========================
# LIFECYCLE MANAGER
# =========================
lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - amcl
      - planner_server
      - controller_server
      - recoveries_server
      - bt_navigator

# =========================
# GLOBAL COSTMAP
# =========================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 1.5
      publish_frequency: 1.0
      static_map: true
      rolling_window: false
      resolution: 0.05
      transform_tolerance: 1.2
      map_type: costmap
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_topic: "/map"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        max_obstacle_height: 0.6
        min_obstacle_height: 0.0
        obstacle_range: 8.0
        raytrace_range: 12.0
        inflation_radius: 0.10
        combination_method: 1
        track_unknown_space: true
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 10
        unknown_threshold: 15
        mark_threshold: 0
        publish_voxel_map: true
        footprint_clearing_enabled: true
        observation_sources: "laser_scan_sensor"
        laser_scan_sensor:
          data_type: LaserScan
          topic: /scan
          marking: true
          clearing: true
          expected_update_rate: 0
          min_obstacle_height: 0.00
          max_obstacle_height: 0.30

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 10.0
        inflation_radius: 0.20

# =========================
# LOCAL COSTMAP
# =========================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_footprint
      update_frequency: 3.0
      publish_frequency: 3.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      transform_tolerance: 1.2
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_topic: "/map"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        max_obstacle_height: 0.6
        min_obstacle_height: 0.0
        obstacle_range: 8.0
        raytrace_range: 12.0
        inflation_radius: 0.10
        combination_method: 1
        track_unknown_space: true
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 10
        unknown_threshold: 15
        mark_threshold: 0
        publish_voxel_map: true
        footprint_clearing_enabled: true
        observation_sources: "laser_scan_sensor"
        laser_scan_sensor:
          data_type: LaserScan
          topic: /scan
          marking: true
          clearing: true
          expected_update_rate: 0
          min_obstacle_height: 0.00
          max_obstacle_height: 0.30

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 10.0
        inflation_radius: 0.20

# =========================
# PLANNER SERVER
# =========================
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      old_navfn_behavior: false
      use_quadratic: true
      use_dijkstra: true
      use_grid_path: false
      allow_unknown: true
      planner_window_x: 0.0
      planner_window_y: 0.0
      default_tolerance: 0.0

# =========================
# CONTROLLER SERVER (TEB LOCAL PLANNER)
# =========================
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 4.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_controller::TebLocalPlannerROS"
      odom_topic: odom
      map_frame: odom
      teb_autosize: True
      dt_ref: 0.45
      dt_hysteresis: 0.1
      global_plan_overwrite_orientation: True
      max_global_plan_lookahead_dist: 3.0
      feasibility_check_no_poses: 5
      max_vel_x: 0.7
      max_vel_x_backwards: 0.35
      max_vel_theta: 2.5
      acc_lim_x: 1.2
      acc_lim_theta: 1.5
      min_turning_radius: 0.0
      footprint_model:
        radius: 0.12
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.5
      free_goal_vel: false
      min_obstacle_dist: 0.20
      include_costmap_obstacles: true
      costmap_obstacles_behind_robot_dist: 1.0
      obstacle_poses_affected: 7
      costmap_converter_plugin: ""
      costmap_converter_spin_thread: true
      costmap_converter_rate: 5
      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: true
      optimization_verbose: false
      penalty_epsilon: 0.1
      weight_max_vel_x: 1
      weight_max_vel_theta: 1
      weight_acc_lim_x: 1
      weight_acc_lim_theta: 1
      weight_kinematics_nh: 1000
      weight_kinematics_forward_drive: 60
      weight_kinematics_turning_radius: 1
      weight_optimaltime: 1
      weight_obstacle: 50
      weight_dynamic_obstacle: 10
      selection_alternative_time_cost: false
      enable_homotopy_class_planning: false
      enable_multithreading: true
      simple_exploration: false
      max_number_classes: 4
      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_keypoint_offset: 0.1
      obstacle_heading_threshold: 0.45
      visualize_hc_graph: false

# =========================
# RECOVERIES SERVER
# =========================
recoveries_server:
  ros__parameters:
    use_sim_time: false
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

